- name: Download nginx
  get_url: url={{nginx_base_url}}/{{nginx_file_name}} dest={{ngnix_install_dir}}
#unpack nginx
- name: Unpack nginx
  command: tar -xvzf {{nginx_file_name}} chdir={{ngnix_install_dir}}
- name: change directory nginx
  shell: chdir={{ngnix_install_dir}}{{nginx_file_tag}} ls #chdir=/etc/nginx-1.8.1 
- name: Compile and install nginx {{ngnix_install_dir}}{{nginx_file_tag}}
  shell: > 
    cd {{ngnix_install_dir}}{{nginx_file_tag}} &&
    ./configure  --prefix=/opt/nginx --user={{nginx_user}} --group={{nginx_user}} --with-http_ssl_module && make && make install
  become: yes
  become_method: sudo
- name: get nginx init script
  get_url: 
    url: http://www.linode.com/docs/assets/1139-init-deb.sh
    dest: "{{ngnix_install_dir}}{{nginx_file_tag}}"
- name: Move init script to etc
  command: mv {{ngnix_install_dir}}{{nginx_file_tag}}/1139-init-deb.sh /etc/init.d/nginx
- name: change file mode
  file: path=/etc/init.d/nginx state=touch mode="a+x"
- name: update nginx file
  shell: /usr/sbin/update-rc.d -f nginx defaults
  become: yes
  become_method: sudo
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
  notify: start nginx


